# Generated by Django 3.1.6 on 2022-12-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='network/static/network/images/default-image.png', null=True, upload_to='media/network/static/network/images'),
        ),
    ]
